action_model:
  save_path: "src/agent_manager/agents/minigrid_keyroom_ppo_agent/submodules/ppo.pth"
  input_shape: [64, 64, 3]
  output_shape: 6
  lr: 2.5e-4
  anneal_lr: True
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatchs: 4
  total_timesteps: 500000
  update_epochs: 4
  clip_coef: 0.2
  norm_adv: True
  clip_vloss: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: 0.01