# maps:
- 
  - "xxxxxxxx"
  - "xxxxxxxx"
  - "xEEx--Gx"
  - "x--x---x"
  - "x--x-xxx"
  - "x------x"
  - "xE---SEx"
  - "xxxxxxxx"
- 
  - "xxxxxxxx"
  - "xxxxxxxx"
  - "xEEx--Gx"
  - "xS-x---x"
  - "x--xDxxx"
  - "x------x"
  - "xE----Ex"
  - "xxxxxxxx"
- 
  - "xxxxxxxx"
  - "xxxxxxxx"
  - "xEEx--Gx"
  - "x--x---x"
  - "xK-xDxxx"
  - "x------x"
  - "xE---SEx"
  - "xxxxxxxx"
